### ISSUE TITLE
npm run start results in Error

### ISSUE THREAD

**Issue by TitusRobyK** [eshaan007/My-Portfolio-v1#2]
Steps to Reproduce
-Clone the project
-run npm i
-run npm run start
Getting the following error

Failed to compile.

./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: No valid exports main found for ~_directoryPath_\My-Portfolio-v1\node_modules\colorette'

Node Version -> v13.3.0

**Comment by eshaan007** [comment]
Updating it soon.. Will Inform when it is ready.. I was at Version 12.14.1.. @TitusRobyK

**Comment by eshaan007** [comment]
Updating it soon.. Will Inform when it is ready.. I was on Node Version 12.14.1.. @TitusRobyK

**Comment by eshaan007** [comment]
Check it out now.. Do close the issue if it is resolved. Regards

**Comment by TitusRobyK** [comment]
Yup , now its working..
